---
version: '3'
services:
  tf-master:
    image: "inc0/issues"
    network_mode: "host"
    ports:
      - "22222:22222"
    restart: "no"
    volumes:
      - "/opt/data/datasets/github:/data"
      - "/opt/data/models/github/model:/model"
    environment:
        TF_CONFIG: '{"cluster":{"master":["localhost:22222"],"ps":["localhost:22223"],"worker":["localhost:22224", "localhost:22225"]},"task":{"type":"master","index":0}}'
  tf-ps:
    image: "inc0/issues"
    network_mode: "host"
    ports:
      - "22223:22223"
    restart: "no"
    volumes:
      - "/opt/data/datasets/github:/data"
      - "/opt/data/models/github/model:/model"
    environment:
        TF_CONFIG: '{"cluster":{"master":["localhost:22222"],"ps":["localhost:22223"],"worker":["localhost:22224", "localhost:22225"]},"task":{"type":"ps","index":0}}'
  tf-worker-1:
    image: "inc0/issues"
    network_mode: "host"
    ports:
      - "22224:22224"
    restart: "no"
    volumes:
      - "/opt/data/datasets/github:/data"
      - "/opt/data/models/github/model:/model"
    environment:
        TF_CONFIG: '{"cluster":{"master":["localhost:22222"],"ps":["localhost:22223"],"worker":["localhost:22224", "localhost:22225"]},"task":{"type":"worker","index":0}}'
  tf-worker-2:
    image: "inc0/issues"
    network_mode: "host"
    ports:
      - "22225:22225"
    restart: "no"
    volumes:
      - "/opt/data/datasets/github:/data"
      - "/opt/data/models/github/model:/model"
    environment:
        TF_CONFIG: '{"cluster":{"master":["localhost:22222"],"ps":["localhost:22223"],"worker":["localhost:22224", "localhost:22225"]},"task":{"type":"worker","index":1}}'
